project:
  type: website
  output-dir: docs
website:
  title: "Patrick D. Mobley"
  image: name.png
  repo-url: https://github.com/patdmob/patdmob.github.io
  repo-actions: [issue]
  cookie-consent:
    style: headline
  page-footer: 
    left: "Copyright © 2022, Patrick D. Mobley" 
  google-analytics:
    tracking-id: UA-122946005-1
    anonymize-ip: true
  favicon: favicon-32x32.png 
  navbar:
    logo: name.png
    logo-alt: "Patrick Mobley"
    title: false
    left:
      - text: Home
        href: index.qmd
      - text: Posts
        href: posts/index.qmd
      - text: Tutorials
        href: tutorials/index.qmd
      - text: Book Reviews
        href: books/index.qmd
      - about.qmd
    right:
      - icon: twitter
        href: https://twitter.com/patdmob/
      - icon: linkedin
        href: https://www.linkedin.com/in/patrickdmobley/
      - icon: github
        href: https://github.com/patdmob/
      - icon: envelope
        href: mailto:patdmob@gmail.com
  comments:
    giscus: 
      repo: patdmob/patdmob.github.io
      repo-id: R_kgDOI-1YBg
      category: Announcements
      category-id: DIC_kwDOI-1YBs4CUQ2J
      mapping: title
      reactions-enabled: true
      input-position: top
      theme: light_protanopia
      loading: lazy
format:
  html:
    theme: lux
    css: styles.css



