<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Patrick D. Mobley">
<meta name="dcterms.date" content="2018-05-16">
<meta name="description" content="A companion notebook to Imbalanced Classification with mlr, here we compare non-SMOTE and SMOTE modeling using logistic regression, decision trees, and randomForest.">

<title>Patrick D. Mobley - Vanilla vs SMOTE Flavored Imbalanced Classification</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../favicon-32x32.png" rel="icon" type="image/png">
<script src="../../site_libs/cookie-consent/cookie-consent.js"></script>
<link href="../../site_libs/cookie-consent/cookie-consent.css" rel="stylesheet">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script async="" src="https://www.googletagmanager.com/gtag/js?id=G-JR92K4JDBK"></script>

<script type="text/plain" cookie-consent="tracking">

window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'G-JR92K4JDBK', { 'anonymize_ip': true});
</script>

<script type="text/javascript" charset="UTF-8">
document.addEventListener('DOMContentLoaded', function () {
cookieconsent.run({
  "notice_banner_type":"headline",
  "consent_type":"implied",
  "palette":"light",
  "language":"en",
  "page_load_consent_levels":["strictly-necessary","functionality","tracking","targeting"],
  "notice_banner_reject_button_hide":false,
  "preferences_center_close_button_hide":false,
  "website_name":""
  });
});
</script> 
  


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../../name.png" alt="Patrick Mobley" class="navbar-logo">
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">
 <span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../posts/index.html">
 <span class="menu-text">Posts</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../tutorials/index.html">
 <span class="menu-text">Tutorials</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../books/index.html">
 <span class="menu-text">Book Reviews</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html">
 <span class="menu-text">About</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://twitter.com/patdmob/"><i class="bi bi-twitter" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/patrickdmobley/"><i class="bi bi-linkedin" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/patdmob/"><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:patdmob@gmail.com"><i class="bi bi-envelope" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul class="collapse">
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#setup" id="toc-setup" class="nav-link" data-scroll-target="#setup">Setup</a></li>
  <li><a href="#benchmarking-logistic-regression" id="toc-benchmarking-logistic-regression" class="nav-link" data-scroll-target="#benchmarking-logistic-regression">Benchmarking Logistic Regression</a></li>
  <li><a href="#benchmarking-decision-tree" id="toc-benchmarking-decision-tree" class="nav-link" data-scroll-target="#benchmarking-decision-tree">Benchmarking Decision Tree</a></li>
  <li><a href="#benchmarking-randomforest" id="toc-benchmarking-randomforest" class="nav-link" data-scroll-target="#benchmarking-randomforest">Benchmarking randomForest</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
<div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/patdmob/patdmob.github.io/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Vanilla vs SMOTE Flavored Imbalanced Classification</h1>
  <div class="quarto-categories">
    <div class="quarto-category">tutorial</div>
    <div class="quarto-category">R programming</div>
    <div class="quarto-category">imbalanced classification</div>
    <div class="quarto-category">data science</div>
  </div>
  </div>

<div>
  <div class="description">
    A companion notebook to Imbalanced Classification with mlr, here we compare non-SMOTE and SMOTE modeling using logistic regression, decision trees, and randomForest.
  </div>
</div>


<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Patrick D. Mobley </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 16, 2018</p>
    </div>
  </div>
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>This is a companion notebook to <a href="../2018-05-15-Imbalanced-Classification-with-mlr"><em>Imbalanced Classification with mlr</em></a>. In this notebook, we investigate whether SMOTE actually improves model performance. For clarity, non-SMOTE models are referred to as <em>“vanilla”</em> models. We compare these two flavors (vanilla and SMOTE) using <strong>logistic regression</strong>, <strong>decision trees</strong>, and <strong>randomForest</strong>. We also consider how tuning model operating thresholds and tuning SMOTE parameters impact the results.</p>
<p>If you must know, I <em>had</em> to make this. We kept debating on the effectiveness of techniques like SMOTE during my lunch break. Eventually, my curiosity won out and here we are. Does SMOTE work? Keep reading to find out! Or just skip to the conclusion.</p>
<p>For more information about this algorithm, check out the <a href="https://arxiv.org/abs/1106.1813">original paper</a>. Or if you’re looking for a visual explanation, <a href="https://limnu.com/smote-visualization-for-data-science/">this post</a> does a good job.</p>
<p>The findings in this notebook represent observed trends but actual results may vary. Additionally, different datasets may respond differently to SMOTE. These findings are not verified by the FDA. ;)</p>
<p>This work was part of a one month PoC for an Employee Attrition Analytics project at Honeywell International. I presented this notebook at a Honeywell internal data science meetup group and received permission to post it publicly. I would like to thank Matt Pettis (Managing Data Scientist), Nabil Ahmed (Solution Architect), Kartik Raval (Data SME), and Jason Fraklin (Business SME). Without their mentorship and contributions, this project would not have been possible.</p>
<section id="a-quick-refresh-on-performance-measures" class="level3">
<h3 class="anchored" data-anchor-id="a-quick-refresh-on-performance-measures">A Quick Refresh on Performance Measures</h3>
<p>There are lots of performance measures to choose from for classification problems. We’ll look at a few to compare these models.</p>
<section id="accuracy" class="level4">
<h4 class="anchored" data-anchor-id="accuracy">Accuracy</h4>
<p>is the percentage of correctly classified instances. However, if the majority class makes up 99% of the data, then it is easy to get an accuracy of 99% by always predicting the majority class. For this reason, accuracy is not a good measure for imbalanced classification problems. 1 - ACC results in the misclassification error or error rate.</p>
<p><img src="./Accuracy.png" class="img-fluid"></p>
</section>
<section id="balanced-accuracy" class="level4">
<h4 class="anchored" data-anchor-id="balanced-accuracy">Balanced Accuracy</h4>
<p>on the other hand, gives equal weight to the relative proportions of negative and positive class instances. If a model predicts only one class, the best balanced accuracy it could receive is 50%. 1 - BAC results in the balanced error rate.</p>
<p><img src="./BalancedAccuracy.png" class="img-fluid"></p>
</section>
<section id="f1-score" class="level4">
<h4 class="anchored" data-anchor-id="f1-score">F1 Score</h4>
<p>is the harmonic mean of precision and recall. A perfect model has a precision and recall of 1 resulting in an F1 score of 1. For all other models, there exists a tradeoff between precision and recall. F1 is a measure that helps us to judge how much of the tradeoff is worthwhile.</p>
<p><img src="./F1.png" class="img-fluid"></p>
<p>or</p>
<p><img src="./F1(2).png" class="img-fluid"></p>
</section>
</section>
</section>
<section id="setup" class="level2">
<h2 class="anchored" data-anchor-id="setup">Setup</h2>
<div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Libraries</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)    <span class="co"># Data manipulation</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mlr)          <span class="co"># Modeling framework</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(parallelMap)  <span class="co"># Parallelization  </span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Parallelization</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">parallelStartSocket</span>(parallel<span class="sc">::</span><span class="fu">detectCores</span>())</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading Data</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">source</span>(<span class="st">"prep_EmployeeAttrition.R"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<section id="defining-the-task" class="level4">
<h4 class="anchored" data-anchor-id="defining-the-task">Defining the Task</h4>
<p>As before, we define the Task at hand: predicting attrition up to four weeks out.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>tsk_4wk <span class="ot">=</span> <span class="fu">makeClassifTask</span>(<span class="at">id =</span> <span class="st">"4 week prediction"</span>,</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>                       <span class="at">data =</span> data <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span><span class="fu">c</span>(<span class="sc">!!</span> exclude)),</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>                       <span class="at">target =</span> <span class="st">"Left4wk"</span>,  <span class="co"># Must be a factor variable</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>                       <span class="at">positive =</span> <span class="st">"Left"</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>                       )</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>tsk_4wk <span class="ot">&lt;-</span> <span class="fu">mergeSmallFactorLevels</span>(tsk_4wk)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">5456</span>)</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>ho_4wk <span class="ot">&lt;-</span> <span class="fu">makeResampleInstance</span>(<span class="st">"Holdout"</span>, tsk_4wk, <span class="at">stratify =</span> <span class="cn">TRUE</span>)   <span class="co"># Default 1/3rd</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>tsk_train_4wk <span class="ot">&lt;-</span> <span class="fu">subsetTask</span>(tsk_4wk, ho_4wk<span class="sc">$</span>train.inds[[<span class="dv">1</span>]])</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>tsk_test_4wk <span class="ot">&lt;-</span> <span class="fu">subsetTask</span>(tsk_4wk, ho_4wk<span class="sc">$</span>test.inds[[<span class="dv">1</span>]])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="defining-the-learners" class="level4">
<h4 class="anchored" data-anchor-id="defining-the-learners">Defining the Learners</h4>
<p>Here we define 3 separate learner lists. Each contains the model with and without SMOTE.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>rate <span class="ot">&lt;-</span> <span class="dv">18</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>neighbors <span class="ot">&lt;-</span> <span class="dv">5</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>logreg_lrns <span class="ot">=</span> <span class="fu">list</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">makeLearner</span>(<span class="st">"classif.logreg"</span>, <span class="at">predict.type =</span> <span class="st">"prob"</span>)</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>  ,<span class="fu">makeSMOTEWrapper</span>(<span class="fu">makeLearner</span>(<span class="st">"classif.logreg"</span>, <span class="at">predict.type =</span> <span class="st">"prob"</span>),</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>                   <span class="at">sw.rate =</span> rate, <span class="at">sw.nn =</span> neighbors))</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>rpart_lrns <span class="ot">=</span> <span class="fu">list</span>(</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">makeLearner</span>(<span class="st">"classif.rpart"</span>, <span class="at">predict.type =</span> <span class="st">"prob"</span>)</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>  ,<span class="fu">makeSMOTEWrapper</span>(<span class="fu">makeLearner</span>(<span class="st">"classif.rpart"</span>, <span class="at">predict.type =</span> <span class="st">"prob"</span>),</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>                   <span class="at">sw.rate =</span> rate, <span class="at">sw.nn =</span> neighbors))</span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>randomForest_lrns <span class="ot">=</span> <span class="fu">list</span>(</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">makeLearner</span>(<span class="st">"classif.randomForest"</span>, <span class="at">predict.type =</span> <span class="st">"prob"</span>)</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>  ,<span class="fu">makeSMOTEWrapper</span>(<span class="fu">makeLearner</span>(<span class="st">"classif.randomForest"</span>, <span class="at">predict.type =</span> <span class="st">"prob"</span>),</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>                   <span class="at">sw.rate =</span> rate, <span class="at">sw.nn =</span> neighbors))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="defining-the-resampling-strategy" class="level4">
<h4 class="anchored" data-anchor-id="defining-the-resampling-strategy">Defining the Resampling Strategy</h4>
<p>Here we define the resampling technique. This strategy is implemented repeatedly throughout this notebook. Each time it chooses different records for each fold accounting for some of the variability between the models.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the resampling technique</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>folds <span class="ot">=</span> <span class="dv">20</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>rdesc <span class="ot">=</span> <span class="fu">makeResampleDesc</span>(<span class="st">"CV"</span>, <span class="at">iters =</span> folds, <span class="at">stratify =</span> <span class="cn">TRUE</span>) <span class="co"># stratification with respect to the target</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
</section>
<section id="benchmarking-logistic-regression" class="level2">
<h2 class="anchored" data-anchor-id="benchmarking-logistic-regression">Benchmarking Logistic Regression</h2>
<p>First, we’ll consider the logistic regression and evaluate how SMOTE impacts model performance.</p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>logreg_bchmk <span class="ot">=</span> <span class="fu">benchmark</span>(logreg_lrns,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>                  tsk_train_4wk,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>                  rdesc, <span class="at">show.info =</span> <span class="cn">FALSE</span>,</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">measures =</span> <span class="fu">list</span>(acc, bac, auc, f1))</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>logreg_bchmk_perf <span class="ot">&lt;-</span> <span class="fu">getBMRAggrPerformances</span>(logreg_bchmk, <span class="at">as.df =</span> <span class="cn">TRUE</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>logreg_bchmk_perf <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>task.id) <span class="sc">%&gt;%</span> knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="table">
<colgroup>
<col style="width: 28%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">learner.id</th>
<th style="text-align: right;">acc.test.mean</th>
<th style="text-align: right;">bac.test.mean</th>
<th style="text-align: right;">auc.test.mean</th>
<th style="text-align: right;">f1.test.mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">classif.logreg</td>
<td style="text-align: right;">0.9290151</td>
<td style="text-align: right;">0.4997191</td>
<td style="text-align: right;">0.8398939</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">classif.logreg.smoted</td>
<td style="text-align: right;">0.6743728</td>
<td style="text-align: right;">0.7880844</td>
<td style="text-align: right;">0.8234845</td>
<td style="text-align: right;">0.2869752</td>
</tr>
</tbody>
</table>
<p>Both models have nearly an identical AUC value of about 0.83. It seems these models effectively trading off accuracy and balanced accuracy. The SMOTE model has a higher balanced accuracy and F1 score of 78.8% and 0.29 respectively (compared to 50% and 0). And the vanilla model has a higher accuracy of 92.9% (compared to 67.4%).</p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize results</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>logreg_df_4wk <span class="ot">=</span> <span class="fu">generateThreshVsPerfData</span>(logreg_bchmk,</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">measures =</span> <span class="fu">list</span>(fpr, tpr, mmce, bac, ppv, tnr, fnr, f1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<section id="roc-curves" class="level4">
<h4 class="anchored" data-anchor-id="roc-curves">ROC Curves</h4>
<div class="sourceCode" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotROCCurves</span>(logreg_df_4wk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./unnamed-chunk-6-1.png" class="img-fluid"></p>
<p>Looking at the ROC curves, we see that they intersect but otherwise have similar performance. It is important to note, in practice, we choose a threshold to operate a model. Therefore, the model with a larger area may not be the model with better performance within a limited threshold range.</p>
</section>
<section id="precision-recall-curves" class="level4">
<h4 class="anchored" data-anchor-id="precision-recall-curves">Precision-Recall Curves</h4>
<div class="sourceCode" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotROCCurves</span>(logreg_df_4wk, <span class="at">measures =</span> <span class="fu">list</span>(tpr, ppv), <span class="at">diagonal =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./unnamed-chunk-7-1.png" class="img-fluid"></p>
<p>Here, if you are considering AUC-PR, the vanilla logistic regression does better than the SMOTEd model. Another thing to note is that the positive predictive value (precision) is fairly low for both models. Even though the AUC looked decent at 0.83 there is still a lot of imprecision in these models. Otherwise, the SMOTE model generally does better when recall (TPR) is high and vice verse for the vanilla model.</p>
</section>
<section id="threshold-plots" class="level4">
<h4 class="anchored" data-anchor-id="threshold-plots">Threshold Plots</h4>
<div class="sourceCode" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotThreshVsPerf</span>(logreg_df_4wk,  <span class="at">measures =</span> <span class="fu">list</span>(fpr, fnr))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./unnamed-chunk-8-1.png" class="img-fluid"></p>
<p>Threshold plots are common visualizations that help determine an appropriate threshold on which to operate. The FPR and FNR clearly illustrate the opposing tradeoff of each model. However it is difficult to compare these models using FPR and FNR since the imbalanced nature of the data has effectively squished the vanilla logistic model to the far left: slope is zero when the threshold is greater than ≈ 0.4.</p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotThreshVsPerf</span>(logreg_df_4wk,  <span class="at">measures =</span> <span class="fu">list</span>(f1, bac))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./unnamed-chunk-9-1.png" class="img-fluid"></p>
<p>For our use case, threshold plots for F1 score and balanced accuracy make it easier to identify good thresholds. And while the vanilla logistic regression is still squished to the left, we can compare the performance peaks for the models. For F1, the vanilla model tends to have a higher peak. Whereas for balanced accuracy, SMOTE tends to have a slightly higher peak. Notice that the balanced accuracy for the SMOTEd model centers around the default threshold of 0.5 whereas the F1 score does not.</p>
</section>
<section id="confusion-matrices" class="level3">
<h3 class="anchored" data-anchor-id="confusion-matrices">Confusion Matrices</h3>
<p>To calculate the confusion matrices, we’ll train a new model using the full training set and predict against the holdout. Before, we only used the training data and aggregated the performance of the 20 cross-validated folds. We separate the data this way to prevent biasing our operating thresholds for these models.</p>
<p>The training set and holdout are defined at the beginning of this notebook and do not change. However, after tuning the SMOTE parameters, we rerun the cross-validation which may result in changes to the SMOTE model and operating thresholds for both models.</p>
<section id="vanilla-logistic-regression-default-threshold" class="level4">
<h4 class="anchored" data-anchor-id="vanilla-logistic-regression-default-threshold">Vanilla Logistic Regression (default threshold)</h4>
<pre><code>        predicted
true     Left Stayed -err.-
  Left      0     67     67
  Stayed    0    884      0
  -err.-    0     67     67

      acc       bac       auc        f1
0.9295478 0.5000000 0.8041298 0.0000000</code></pre>
<p>If you just look at accuracy (93%), this model performs great! But it is useless for the business. This model predicted that 0 employees would leave in the next 4 weeks but actually 67 left. This is why we need balanced performance measures like balanced accuracy for imbalanced classification problems. The balanced accuracy of 50% clearly illustrates the problem of this model.</p>
</section>
<section id="smote-logistic-regression-default-threshold" class="level4">
<h4 class="anchored" data-anchor-id="smote-logistic-regression-default-threshold">SMOTE Logistic Regression (default threshold)</h4>
<pre><code>        predicted
true     Left Stayed -err.-
  Left     56     11     11
  Stayed  277    607    277
  -err.-  277     11    288

      acc       bac       auc        f1
0.6971609 0.7612362 0.8177382 0.2800000</code></pre>
<p>This is the first evidence that SMOTE works. We have a more balanced model (76.1% balanced accuracy compared to 50%) that might actually be useful for the business. It narrows the pool of employees at risk of attrition from 951 down to 333 while capturing 83.6% of employees that actually left. If this were the only information available, then SMOTE does appear to result in a better model.</p>
<p>However the AUC is similar for both models indicating similar performance. As mentioned earlier, we can operate these models at different thresholds.</p>
</section>
<section id="tuning-the-operating-threshold" class="level4">
<h4 class="anchored" data-anchor-id="tuning-the-operating-threshold">Tuning the Operating Threshold</h4>
<p>The following code tunes the operating threshold for each model:</p>
<div class="sourceCode" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>metric <span class="ot">&lt;-</span> f1</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>logreg_thresh_vanilla <span class="ot">&lt;-</span> <span class="fu">tuneThreshold</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>                             <span class="fu">getBMRPredictions</span>(logreg_bchmk</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>                                  ,<span class="at">learner.ids =</span><span class="st">"classif.logreg"</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>                                  ,<span class="at">drop =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>                             ,<span class="at">measure =</span> metric)</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>logreg_thresh_SMOTE <span class="ot">&lt;-</span> <span class="fu">tuneThreshold</span>(</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>                             <span class="fu">getBMRPredictions</span>(logreg_bchmk</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>                                  ,<span class="at">learner.ids =</span><span class="st">"classif.logreg.smoted"</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>                                  ,<span class="at">drop =</span> <span class="cn">TRUE</span>)</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>                             ,<span class="at">measure =</span> metric)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Here we’ve tuned these models using the F1 measure but we could have easily used a different metric.</p>
</section>
<section id="vanilla-logistic-regression-tuned-threshold" class="level4">
<h4 class="anchored" data-anchor-id="vanilla-logistic-regression-tuned-threshold">Vanilla Logistic Regression (tuned threshold)</h4>
<pre><code>        predicted
true     Left Stayed -err.-
  Left     29     38     38
  Stayed  130    754    130
  -err.-  130     38    168

      acc       bac       auc        f1
0.8233438 0.6428885 0.8041298 0.2566372</code></pre>
</section>
<section id="smote-logistic-regression-tuned-threshold" class="level4">
<h4 class="anchored" data-anchor-id="smote-logistic-regression-tuned-threshold">SMOTE Logistic Regression (tuned threshold)</h4>
<pre><code>        predicted
true     Left Stayed -err.-
  Left     39     28     28
  Stayed  164    720    164
  -err.-  164     28    192

      acc       bac       auc        f1
0.7981073 0.6982846 0.8177382 0.2888889</code></pre>
<p>Setting the tuned operating threshold results in two very similar models! Depending on the run, there might be a slight benefit to the SMOTEd model, but not enough to say with confidence.</p>
<p>But perhaps SMOTE just needs some tuning.</p>
</section>
<section id="tuning-smote" class="level4">
<h4 class="anchored" data-anchor-id="tuning-smote">Tuning SMOTE</h4>
<p>The SMOTE algorithm is defined by the parameters <em>rate</em> and <em>nearest neighbors</em>. <em>Rate</em> defines how much to oversample the minority class. <em>Nearest neighbors</em> defines how many nearest neighbors to consider. Tuning these should result in better model performance.</p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>logreg_ps <span class="ot">=</span> <span class="fu">makeParamSet</span>(</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>              <span class="fu">makeIntegerParam</span>(<span class="st">"sw.rate"</span>, <span class="at">lower =</span> 8L, <span class="at">upper =</span> 28L)</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>              ,<span class="fu">makeIntegerParam</span>(<span class="st">"sw.nn"</span>, <span class="at">lower =</span> 2L, <span class="at">upper =</span> 8L)</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>              )</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>ctrl <span class="ot">=</span> <span class="fu">makeTuneControlIrace</span>(<span class="at">maxExperiments =</span> 400L)</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>logreg_tr <span class="ot">=</span> <span class="fu">tuneParams</span>(logreg_lrns[[<span class="dv">2</span>]], tsk_train_4wk, rdesc, <span class="fu">list</span>(f1, bac), logreg_ps, ctrl)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>logreg_lrns[[<span class="dv">2</span>]] <span class="ot">=</span> <span class="fu">setHyperPars</span>(logreg_lrns[[<span class="dv">2</span>]], <span class="at">par.vals=</span>logreg_tr<span class="sc">$</span>x)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>logreg_bchmk <span class="ot">=</span> <span class="fu">benchmark</span>(logreg_lrns,</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>                  tsk_train_4wk,</span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>                  rdesc, <span class="at">show.info =</span> <span class="cn">FALSE</span>,</span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>                  <span class="at">measures =</span> <span class="fu">list</span>(acc, bac, auc, f1))</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>logreg_thresh_vanilla <span class="ot">&lt;-</span> <span class="fu">tuneThreshold</span>(</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">getBMRPredictions</span>(logreg_bchmk</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">learner.ids =</span><span class="st">"classif.logreg"</span></span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">drop =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">measure =</span> metric)</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>logreg_thresh_SMOTE <span class="ot">&lt;-</span> <span class="fu">tuneThreshold</span>(</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">getBMRPredictions</span>(logreg_bchmk</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">learner.ids =</span><span class="st">"classif.logreg.smoted"</span></span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">drop =</span> <span class="cn">TRUE</span>),</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">measure =</span> metric)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="vanilla-logistic-regression-tuned-threshold-1" class="level4">
<h4 class="anchored" data-anchor-id="vanilla-logistic-regression-tuned-threshold-1">Vanilla Logistic Regression (tuned threshold)</h4>
<pre><code>        predicted
true     Left Stayed -err.-
  Left     35     32     32
  Stayed  145    739    145
  -err.-  145     32    177

      acc       bac       auc        f1
0.8138801 0.6791805 0.8041298 0.2834008</code></pre>
</section>
<section id="smote-logistic-regression-tuned-threshold-and-smote" class="level4">
<h4 class="anchored" data-anchor-id="smote-logistic-regression-tuned-threshold-and-smote">SMOTE Logistic Regression (tuned threshold and SMOTE)</h4>
<pre><code>        predicted
true     Left Stayed -err.-
  Left     42     25     25
  Stayed  182    702    182
  -err.-  182     25    207

      acc       bac       auc        f1
0.7823344 0.7104917 0.8105795 0.2886598</code></pre>
<p>If we account for resampling variance, the tuned SMOTE makes little difference. Perhaps the initial SMOTE parameters close enough to the optimal settings. This table shows how they changed:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;">Rate</th>
<th style="text-align: center;">Nearest Neighbors</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Initial</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: right;">Tuned</td>
<td style="text-align: center;">9</td>
<td style="text-align: center;">2</td>
</tr>
</tbody>
</table>
<p>The rate decreased by 9 and the number of nearest neighbors decreased by 3.</p>
<p>After running this code multiple times, SMOTE generally produces models with higher balanced accuracy but lower accuracy. In terms of AUC and F1, it is harder to tell. Either way, even if SMOTE is tuned, observed performance increases are small compared to a vanilla logistic model with a tuned operating threshold. These results may also depend on the data itself. A different dataset intended to solve another imbalanced classification problem may have different results using SMOTE with logistic regression.</p>
</section>
</section>
</section>
<section id="benchmarking-decision-tree" class="level2">
<h2 class="anchored" data-anchor-id="benchmarking-decision-tree">Benchmarking Decision Tree</h2>
<div class="sourceCode" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>rpart_bchmk <span class="ot">=</span> <span class="fu">benchmark</span>(rpart_lrns,</span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>                  tsk_train_4wk,</span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>                  rdesc, <span class="at">show.info =</span> <span class="cn">FALSE</span>,</span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">measures =</span> <span class="fu">list</span>(acc, bac, auc, f1))</span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>rpart_bchmk_perf <span class="ot">&lt;-</span> <span class="fu">getBMRAggrPerformances</span>(rpart_bchmk, <span class="at">as.df =</span> <span class="cn">TRUE</span>)</span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>rpart_bchmk_perf <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>task.id) <span class="sc">%&gt;%</span> knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="table">
<colgroup>
<col style="width: 27%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 18%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">learner.id</th>
<th style="text-align: right;">acc.test.mean</th>
<th style="text-align: right;">bac.test.mean</th>
<th style="text-align: right;">auc.test.mean</th>
<th style="text-align: right;">f1.test.mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">classif.rpart</td>
<td style="text-align: right;">0.9290539</td>
<td style="text-align: right;">0.5888060</td>
<td style="text-align: right;">0.6995163</td>
<td style="text-align: right;">0.2594619</td>
</tr>
<tr class="even">
<td style="text-align: left;">classif.rpart.smoted</td>
<td style="text-align: right;">0.7491146</td>
<td style="text-align: right;">0.7771476</td>
<td style="text-align: right;">0.8605376</td>
<td style="text-align: right;">0.3113137</td>
</tr>
</tbody>
</table>
<p>Let’s be honest, the SMOTEd logistic regression was lackluster. But for the decision tree model, SMOTE increases AUC by 0.16. Both flavors have similar F1 scores; otherwise we see the same tradeoff between accuracy and balanced accuracy as in the logistic regression.</p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize results</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>rpart_df_4wk <span class="ot">=</span> <span class="fu">generateThreshVsPerfData</span>(rpart_bchmk,</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">measures =</span> <span class="fu">list</span>(fpr, tpr, mmce, bac, ppv, tnr, fnr, f1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<section id="roc-curves-1" class="level4">
<h4 class="anchored" data-anchor-id="roc-curves-1">ROC Curves</h4>
<div class="sourceCode" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotROCCurves</span>(rpart_df_4wk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./unnamed-chunk-20-1.png" class="img-fluid"></p>
<p>It’s easy to see that SMOTE has a higher AUC than the vanilla model, but since the lines cross, each perform better within certain operating thresholds.</p>
</section>
<section id="precision-recall-curves-1" class="level4">
<h4 class="anchored" data-anchor-id="precision-recall-curves-1">Precision-Recall Curves</h4>
<div class="sourceCode" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotROCCurves</span>(rpart_df_4wk, <span class="at">measures =</span> <span class="fu">list</span>(tpr, ppv), <span class="at">diagonal =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./unnamed-chunk-21-1.png" class="img-fluid"></p>
<p>The vanilla model scores much higher on precision (PPV) but declines much more quickly as recall increases. SMOTE is more precise when recall (TPR) is greater than ≈ 0.75. Additionally, notice the straight lines, likely, there are no data in these regions making each model only viable for half the PR Curve.</p>
</section>
<section id="threshold-plots-1" class="level4">
<h4 class="anchored" data-anchor-id="threshold-plots-1">Threshold Plots</h4>
<div class="sourceCode" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotThreshVsPerf</span>(rpart_df_4wk,  <span class="at">measures =</span> <span class="fu">list</span>(fpr, fnr))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./unnamed-chunk-22-1.png" class="img-fluid"></p>
<p>The nearly vertical slopes of these threshold plots represent the straight lines on the PR Curve plot.</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotThreshVsPerf</span>(rpart_df_4wk,  <span class="at">measures =</span> <span class="fu">list</span>(f1, bac))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./unnamed-chunk-23-1.png" class="img-fluid"></p>
<p>If we’re concerned primarily with balanced accuracy, SMOTE is clearly better at all thresholds. For the F1 score however, it depends on the operating threshold of the model. Notice balanced accuracy is once again centered around the default threshold of 0.5 and the F1 measure is not. The F1 performance to threshold pattern is roughly opposite for the two flavors of decision trees.</p>
</section>
<section id="confusion-matrices-1" class="level3">
<h3 class="anchored" data-anchor-id="confusion-matrices-1">Confusion Matrices</h3>
<section id="vanilla-decision-tree-default-threshold" class="level4">
<h4 class="anchored" data-anchor-id="vanilla-decision-tree-default-threshold">Vanilla Decision Tree (default threshold)</h4>
<pre><code>        predicted
true     Left Stayed -err.-
  Left     10     57     57
  Stayed    7    877      7
  -err.-    7     57     64

      acc       bac       auc        f1
0.9327024 0.5706676 0.7061694 0.2380952</code></pre>
<p>Using the default threshold, the vanilla decision tree manages to identify some employee attrition. In face, its accuracy of 93.3% is higher than the baseline case of always predicting the majority class (93%). It is relatively precise (0.59) but has low recall (0.15). Overall accuracy is high (93.3%), but the model is not very balanced (57.1%).</p>
</section>
<section id="smote-decision-tree-default-threshold" class="level4">
<h4 class="anchored" data-anchor-id="smote-decision-tree-default-threshold">SMOTE Decision Tree (default threshold)</h4>
<pre><code>        predicted
true     Left Stayed -err.-
  Left     55     12     12
  Stayed  232    652    232
  -err.-  232     12    244

      acc       bac       auc        f1
0.7434280 0.7792260 0.8338117 0.3107345</code></pre>
<p>The SMOTE Decision Tree does a much better job of capturing employees that left (82% compared to 15%) but at the cost of precision. The model identifies 287 when only 55 from that group actually leave. Still this model is more useful to the business than the vanilla decision tree at the default threshold.</p>
</section>
<section id="tuning-the-operating-threshold-1" class="level4">
<h4 class="anchored" data-anchor-id="tuning-the-operating-threshold-1">Tuning the Operating Threshold</h4>
<div class="sourceCode" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>rpart_thresh_vanilla <span class="ot">&lt;-</span> <span class="fu">tuneThreshold</span>(</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">getBMRPredictions</span>(rpart_bchmk</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">learner.ids =</span><span class="st">"classif.rpart"</span></span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">drop =</span> <span class="cn">TRUE</span>),</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">measure =</span> metric)</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>rpart_thresh_SMOTE <span class="ot">&lt;-</span> <span class="fu">tuneThreshold</span>(</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">getBMRPredictions</span>(rpart_bchmk</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">learner.ids =</span><span class="st">"classif.rpart.smoted"</span></span>
<span id="cb27-9"><a href="#cb27-9" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">drop =</span> <span class="cn">TRUE</span>),</span>
<span id="cb27-10"><a href="#cb27-10" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">measure =</span> metric)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>As before, we’ll be using the F1 measure.</p>
</section>
<section id="vanilla-decision-tree-tuned-threshold" class="level4">
<h4 class="anchored" data-anchor-id="vanilla-decision-tree-tuned-threshold">Vanilla Decision Tree (tuned threshold)</h4>
<pre><code>        predicted
true     Left Stayed -err.-
  Left     22     45     45
  Stayed   26    858     26
  -err.-   26     45     71

      acc       bac       auc        f1
0.9253417 0.6494732 0.7061694 0.3826087</code></pre>
<p>Once we tune the threshold, the vanilla decision tree model performs much better–identifying more employees that leave with relatively high precision. The F1 score increases from 0.238 to 0.383.</p>
</section>
<section id="smote-decision-tree-tuned-threshold" class="level4">
<h4 class="anchored" data-anchor-id="smote-decision-tree-tuned-threshold">SMOTE Decision Tree (tuned threshold)</h4>
<pre><code>        predicted
true     Left Stayed -err.-
  Left     32     35     35
  Stayed   80    804     80
  -err.-   80     35    115

      acc       bac       auc        f1
0.8790747 0.6935571 0.8338117 0.3575419</code></pre>
<p>Changing the operating threshold for the SMOTEd decision tree results in a 13.6% higher accuracy, 8.57% lower balanced accuracy, and higher F1 measure of 4.68%.</p>
<p>These changes to the operating threshold result in a similar F1 performance for both flavors of decision tree (0.358 compared to 0.383).</p>
</section>
<section id="tuning-smote-1" class="level4">
<h4 class="anchored" data-anchor-id="tuning-smote-1">Tuning SMOTE</h4>
<div class="sourceCode" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>rpart_ps <span class="ot">=</span> <span class="fu">makeParamSet</span>(</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>              <span class="fu">makeIntegerParam</span>(<span class="st">"sw.rate"</span>, <span class="at">lower =</span> 8L, <span class="at">upper =</span> 28L)</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>              ,<span class="fu">makeIntegerParam</span>(<span class="st">"sw.nn"</span>, <span class="at">lower =</span> 2L, <span class="at">upper =</span> 8L)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>              )</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>ctrl <span class="ot">=</span> <span class="fu">makeTuneControlIrace</span>(<span class="at">maxExperiments =</span> 200L)</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>rpart_tr <span class="ot">=</span> <span class="fu">tuneParams</span>(rpart_lrns[[<span class="dv">2</span>]], tsk_train_4wk, rdesc, <span class="fu">list</span>(f1, bac), rpart_ps, ctrl)</span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a>rpart_lrns[[<span class="dv">2</span>]] <span class="ot">=</span> <span class="fu">setHyperPars</span>(rpart_lrns[[<span class="dv">2</span>]], <span class="at">par.vals=</span>rpart_tr<span class="sc">$</span>x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>rpart_bchmk <span class="ot">=</span> <span class="fu">benchmark</span>(rpart_lrns,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>                  tsk_train_4wk,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>                  rdesc, <span class="at">show.info =</span> <span class="cn">FALSE</span>,</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">measures =</span> <span class="fu">list</span>(acc, bac, auc, f1))</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>rpart_thresh_vanilla <span class="ot">&lt;-</span> <span class="fu">tuneThreshold</span>(</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">getBMRPredictions</span>(rpart_bchmk</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">learner.ids =</span><span class="st">"classif.rpart"</span></span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">drop =</span> <span class="cn">TRUE</span>),</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">measure =</span> metric)</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a>rpart_thresh_SMOTE <span class="ot">&lt;-</span> <span class="fu">tuneThreshold</span>(</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">getBMRPredictions</span>(rpart_bchmk</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">learner.ids =</span><span class="st">"classif.rpart.smoted"</span></span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">drop =</span> <span class="cn">TRUE</span>),</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">measure =</span> metric)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="vanilla-decision-tree-tuned-threshold-1" class="level4">
<h4 class="anchored" data-anchor-id="vanilla-decision-tree-tuned-threshold-1">Vanilla Decision Tree (tuned threshold)</h4>
<pre><code>        predicted
true     Left Stayed -err.-
  Left     23     44     44
  Stayed   35    849     35
  -err.-   35     44     79

      acc       bac       auc        f1
0.9169295 0.6518454 0.7061694 0.3680000</code></pre>
</section>
<section id="smote-decision-tree-tuned-threshold-and-smote" class="level4">
<h4 class="anchored" data-anchor-id="smote-decision-tree-tuned-threshold-and-smote">SMOTE Decision Tree (tuned threshold and SMOTE)</h4>
<pre><code>        predicted
true     Left Stayed -err.-
  Left     32     35     35
  Stayed   80    804     80
  -err.-   80     35    115

      acc       bac       auc        f1
0.8790747 0.6935571 0.7885628 0.3575419</code></pre>
<p>Tuning SMOTE for the decision tree changed the accuracy from 87.9% to 87.9% and the balanced accuracy from 69.4% to 69.4%. The following table shows how the rate and number of nearest neighbors changed:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;">Rate</th>
<th style="text-align: center;">Nearest Neighbors</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Initial</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: right;">Tuned</td>
<td style="text-align: center;">15</td>
<td style="text-align: center;">7</td>
</tr>
</tbody>
</table>
<p>The rate decreased by 3 and the number of nearest neighbors increased by 2.</p>
<p>Given our data, SMOTE for decision trees seems to offer real performance increases to the model. That said, the performance increases are largely via tradeoff between accuracy and balanced accuracy. Setting the operating threshold for the vanilla model results in a similarly performant model. However, we need to consider that identifying rare events is our primary concern. SMOTE allows us to operate with increased performance when high recall is important.</p>
</section>
</section>
</section>
<section id="benchmarking-randomforest" class="level2">
<h2 class="anchored" data-anchor-id="benchmarking-randomforest">Benchmarking randomForest</h2>
<div class="sourceCode" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>randomForest_bchmk <span class="ot">=</span> <span class="fu">benchmark</span>(randomForest_lrns,</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a>                  tsk_train_4wk,</span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a>                  rdesc, <span class="at">show.info =</span> <span class="cn">FALSE</span>,</span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">measures =</span> <span class="fu">list</span>(acc, bac, auc, f1))</span>
<span id="cb34-6"><a href="#cb34-6" aria-hidden="true" tabindex="-1"></a>randomForest_bchmk_perf <span class="ot">&lt;-</span> <span class="fu">getBMRAggrPerformances</span>(randomForest_bchmk, <span class="at">as.df =</span> <span class="cn">TRUE</span>)</span>
<span id="cb34-7"><a href="#cb34-7" aria-hidden="true" tabindex="-1"></a>randomForest_bchmk_perf <span class="sc">%&gt;%</span> <span class="fu">select</span>(<span class="sc">-</span>task.id) <span class="sc">%&gt;%</span> knitr<span class="sc">::</span><span class="fu">kable</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<table class="table">
<colgroup>
<col style="width: 32%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">learner.id</th>
<th style="text-align: right;">acc.test.mean</th>
<th style="text-align: right;">bac.test.mean</th>
<th style="text-align: right;">auc.test.mean</th>
<th style="text-align: right;">f1.test.mean</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">classif.randomForest</td>
<td style="text-align: right;">0.9310609</td>
<td style="text-align: right;">0.5878136</td>
<td style="text-align: right;">0.8942103</td>
<td style="text-align: right;">0.2674242</td>
</tr>
<tr class="even">
<td style="text-align: left;">classif.randomForest.smoted</td>
<td style="text-align: right;">0.8868540</td>
<td style="text-align: right;">0.7553178</td>
<td style="text-align: right;">0.8875052</td>
<td style="text-align: right;">0.4339340</td>
</tr>
</tbody>
</table>
<p>For the randomForest models, we see similar patters as for the logistic regression and decision tress. There is a trade off between accuracy and balanced accuracy. Unlike the decision tree models, SMOTE does not improve AUC for SMOTE randomForest (both are ≈ 0.89).</p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualize results</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>randomForest_df_4wk <span class="ot">=</span> <span class="fu">generateThreshVsPerfData</span>(randomForest_bchmk,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>            <span class="at">measures =</span> <span class="fu">list</span>(fpr, tpr, mmce, bac, ppv, tnr, fnr, f1))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<section id="roc-curves-2" class="level4">
<h4 class="anchored" data-anchor-id="roc-curves-2">ROC Curves</h4>
<div class="sourceCode" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotROCCurves</span>(randomForest_df_4wk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./unnamed-chunk-35-1.png" class="img-fluid"></p>
<p>Both models cross multiple times showing either model is likely good for most thresholds.</p>
</section>
<section id="precision-recall-curves-2" class="level4">
<h4 class="anchored" data-anchor-id="precision-recall-curves-2">Precision-Recall Curves</h4>
<div class="sourceCode" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotROCCurves</span>(randomForest_df_4wk, <span class="at">measures =</span> <span class="fu">list</span>(tpr, ppv), <span class="at">diagonal =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./unnamed-chunk-36-1.png" class="img-fluid"></p>
<p>This PR-Curve shows more distinctly that SMOTE generally performs better when recall is high, whereas the vanilla model generally performs better when recall is lower.</p>
</section>
<section id="threshold-plots-2" class="level4">
<h4 class="anchored" data-anchor-id="threshold-plots-2">Threshold Plots</h4>
<div class="sourceCode" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotThreshVsPerf</span>(randomForest_df_4wk,  <span class="at">measures =</span> <span class="fu">list</span>(fpr, fnr))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./unnamed-chunk-37-1.png" class="img-fluid"></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plotThreshVsPerf</span>(randomForest_df_4wk,  <span class="at">measures =</span> <span class="fu">list</span>(f1, bac))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="./unnamed-chunk-38-1.png" class="img-fluid"></p>
<p>Interestingly, the SMOTE randomForest does not center balanced accuracy around the default threshold; rather F1 is centered on the 0.5 threshold. Otherwise we see that SMOTE produces a higher peak for balanced accuracy but lower for F1. Additionally, the vanilla model is still squished to the left due to its class imbalance.</p>
</section>
<section id="confusion-matrices-2" class="level3">
<h3 class="anchored" data-anchor-id="confusion-matrices-2">Confusion Matrices</h3>
<section id="vanilla-randomforest-default-threshold" class="level4">
<h4 class="anchored" data-anchor-id="vanilla-randomforest-default-threshold">Vanilla randomForest (default threshold)</h4>
<pre><code>        predicted
true     Left Stayed -err.-
  Left     15     52     52
  Stayed    7    877      7
  -err.-    7     52     59

      acc       bac       auc        f1
0.9379600 0.6079810 0.8559718 0.3370787</code></pre>
<p>As far as vanilla models go, and given the default threshold, the randomForest performs the best. That said, this model captures very few employees that leave.</p>
</section>
<section id="smote-randomforest-default-threshold" class="level4">
<h4 class="anchored" data-anchor-id="smote-randomforest-default-threshold">SMOTE randomForest (default threshold)</h4>
<pre><code>        predicted
true     Left Stayed -err.-
  Left     34     33     33
  Stayed   78    806     78
  -err.-   78     33    111

      acc       bac       auc        f1
0.8832808 0.7096137 0.8686263 0.3798883</code></pre>
<p>The SMOTEd randomForest also does well. The accuracy is high and manages a good balanced accuracy.</p>
</section>
<section id="tuning-the-operating-threshold-2" class="level4">
<h4 class="anchored" data-anchor-id="tuning-the-operating-threshold-2">Tuning the Operating Threshold</h4>
<div class="sourceCode" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>randomForest_thresh_vanilla <span class="ot">&lt;-</span> <span class="fu">tuneThreshold</span>(</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">getBMRPredictions</span>(randomForest_bchmk</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">learner.ids =</span><span class="st">"classif.randomForest"</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">drop =</span> <span class="cn">TRUE</span>),</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">measure =</span> metric)</span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>randomForest_thresh_SMOTE <span class="ot">&lt;-</span> <span class="fu">tuneThreshold</span>(</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">getBMRPredictions</span>(randomForest_bchmk</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">learner.ids =</span><span class="st">"classif.randomForest.smoted"</span></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">drop =</span> <span class="cn">TRUE</span>),</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">measure =</span> metric)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>As before, we’ll be using the F1 measure.</p>
</section>
<section id="vanilla-randomforest-tuned-threshold" class="level4">
<h4 class="anchored" data-anchor-id="vanilla-randomforest-tuned-threshold">Vanilla randomForest (tuned threshold)</h4>
<pre><code>        predicted
true     Left Stayed -err.-
  Left     38     29     29
  Stayed   78    806     78
  -err.-   78     29    107

      acc       bac       auc        f1
0.8874869 0.7394644 0.8559718 0.4153005</code></pre>
</section>
<section id="smote-randomforest-tuned-threshold" class="level4">
<h4 class="anchored" data-anchor-id="smote-randomforest-tuned-threshold">SMOTE randomForest (tuned threshold)</h4>
<pre><code>        predicted
true     Left Stayed -err.-
  Left     36     31     31
  Stayed   81    803     81
  -err.-   81     31    112

      acc       bac       auc        f1
0.8822292 0.7228422 0.8686263 0.3913043</code></pre>
<p>At the tuned threshold, the performance of both flavors perform better and are once again very similar. Depending on the run, SMOTE will have a higher balanced accuracy, but otherwise there is little difference between the models.</p>
</section>
<section id="tuning-smote-2" class="level4">
<h4 class="anchored" data-anchor-id="tuning-smote-2">Tuning SMOTE</h4>
<div class="sourceCode" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>randomForest_ps <span class="ot">=</span> <span class="fu">makeParamSet</span>(</span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>              <span class="fu">makeIntegerParam</span>(<span class="st">"sw.rate"</span>, <span class="at">lower =</span> 8L, <span class="at">upper =</span> 28L)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>              ,<span class="fu">makeIntegerParam</span>(<span class="st">"sw.nn"</span>, <span class="at">lower =</span> 2L, <span class="at">upper =</span> 8L)</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>              )</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>ctrl <span class="ot">=</span> <span class="fu">makeTuneControlIrace</span>(<span class="at">maxExperiments =</span> 200L)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>randomForest_tr <span class="ot">=</span> <span class="fu">tuneParams</span>(randomForest_lrns[[<span class="dv">2</span>]], tsk_train_4wk, rdesc, <span class="fu">list</span>(f1, bac), randomForest_ps, ctrl)</span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a>randomForest_lrns[[<span class="dv">2</span>]] <span class="ot">=</span> <span class="fu">setHyperPars</span>(randomForest_lrns[[<span class="dv">2</span>]], <span class="at">par.vals=</span>randomForest_tr<span class="sc">$</span>x)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the model</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>randomForest_bchmk <span class="ot">=</span> <span class="fu">benchmark</span>(randomForest_lrns,</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>                  tsk_train_4wk,</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>                  rdesc, <span class="at">show.info =</span> <span class="cn">FALSE</span>,</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a>                  <span class="at">measures =</span> <span class="fu">list</span>(acc, bac, auc, f1))</span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>randomForest_thresh_vanilla <span class="ot">&lt;-</span> <span class="fu">tuneThreshold</span>(</span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">getBMRPredictions</span>(randomForest_bchmk</span>
<span id="cb46-8"><a href="#cb46-8" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">learner.ids =</span><span class="st">"classif.randomForest"</span></span>
<span id="cb46-9"><a href="#cb46-9" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">drop =</span> <span class="cn">TRUE</span>),</span>
<span id="cb46-10"><a href="#cb46-10" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">measure =</span> metric)</span>
<span id="cb46-11"><a href="#cb46-11" aria-hidden="true" tabindex="-1"></a>randomForest_thresh_SMOTE <span class="ot">&lt;-</span> <span class="fu">tuneThreshold</span>(</span>
<span id="cb46-12"><a href="#cb46-12" aria-hidden="true" tabindex="-1"></a>                                  <span class="fu">getBMRPredictions</span>(randomForest_bchmk</span>
<span id="cb46-13"><a href="#cb46-13" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">learner.ids =</span><span class="st">"classif.randomForest.smoted"</span></span>
<span id="cb46-14"><a href="#cb46-14" aria-hidden="true" tabindex="-1"></a>                                                    ,<span class="at">drop =</span> <span class="cn">TRUE</span>),</span>
<span id="cb46-15"><a href="#cb46-15" aria-hidden="true" tabindex="-1"></a>                                  <span class="at">measure =</span> metric)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="vanilla-randomforest-tuned-threshold-1" class="level4">
<h4 class="anchored" data-anchor-id="vanilla-randomforest-tuned-threshold-1">Vanilla randomForest (tuned threshold)</h4>
<pre><code>        predicted
true     Left Stayed -err.-
  Left     40     27     27
  Stayed  101    783    101
  -err.-  101     27    128

      acc       bac       auc        f1
0.8654048 0.7413808 0.8527470 0.3846154</code></pre>
</section>
<section id="smote-randomforest-tuned-threshold-and-smote" class="level4">
<h4 class="anchored" data-anchor-id="smote-randomforest-tuned-threshold-and-smote">SMOTE randomForest (tuned threshold and SMOTE)</h4>
<pre><code>        predicted
true     Left Stayed -err.-
  Left     37     30     30
  Stayed   98    786     98
  -err.-   98     30    128

      acc       bac       auc        f1
0.8654048 0.7206895 0.8637384 0.3663366</code></pre>
<p>Given this data, tuning SMOTE does not seem to improve performance. The following table shows how the parameters for SMOTE changed during the tuning process:</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;"></th>
<th style="text-align: center;">Rate</th>
<th style="text-align: center;">Nearest Neighbors</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">Initial</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">5</td>
</tr>
<tr class="even">
<td style="text-align: right;">Tuned</td>
<td style="text-align: center;">18</td>
<td style="text-align: center;">3</td>
</tr>
</tbody>
</table>
<p>The rate did not change and the number of nearest neighbors decreased by 2.</p>
<p>Given this data for randomForest, SMOTE does little to improve model performance. At optimized operating thresholds, both flavors end up with very similar accuracy and balanced accuracy. There does appear to be some benefit using SMOTE where recall is high and precision is low, however the business may not want to throw such a large net in order to capture all of the employees that leave. Practically speaking, SMOTE did not improve the performance for this problem when using randomForest.</p>
<div class="sourceCode" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="fu">parallelStop</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<pre><code>Stopped parallelization. All cleaned up.</code></pre>
</section>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>Given this data, SMOTE improved AUC of the decision tree model but offered little improvement for logistic regression or randomForest. Otherwise, SMOTE offered a way to trade accuracy for balanced accuracy. For our problem of employee attrition, this trade off is worth it to continue using SMOTE. Even when operating thresholds are optimized, there is–at worst–no change in the performance of the models. That said, the ideal solution might be an ensemble of SMOTE and vanilla models at operating thresholds suited for their flavor.</p>
<p>This notebook shows SMOTE impacts models differently, a finding supported by <a href="http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.79.4356&amp;rep=rep1&amp;type=pdf">Experimental Perspectives on Learning from Imbalanced Data</a>. They also found, while generally beneficial, SMOTE often did not perform as well as simple random undersampling–something we might try in a future notebook. A different paper, <a href="https://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-14-106">SMOTE for high-dimensional class-imbalanced data</a>, found that for high-dimensional data, SMOTE is beneficial but only after variable selection is performed. The employee attrition problem featured here does not have high-dimensional data, however it is useful to consider how feature selection may impact the calculated Euclidean distance used in the SMOTE algorithm. If we gather more features, it may be beneficial to perform more rigorous feature selection before SMOTE to improve model performance.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<script src="https://giscus.app/client.js" data-repo="patdmob/patdmob.github.io" data-repo-id="R_kgDOI-1YBg" data-category="Announcements" data-category-id="DIC_kwDOI-1YBs4CUQ2J" data-mapping="title" data-reactions-enabled="1" data-emit-metadata="0" data-input-position="top" data-theme="light_protanopia" data-lang="en" crossorigin="anonymous" data-loading="lazy" async="">
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">Copyright © 2022, Patrick D. Mobley</div>   
      <div class="nav-footer-center"><div class="cookie-consent-footer"><a href="#" id="open_preferences_center">Cookie Preferences</a></div></div>
  </div>
</footer>



</body></html>